import Discover from "@/components/Discover";
import TrendingSection from "@/components/TrendingSection";
import Head from "next/head";

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="w-container ml-auto mr-auto">
        <Discover/>
        <TrendingSection/>
      </main>
    </>
  );
}
